version: '3.4'

services:
  db:
    image: postgres:12
    # restart: always
    hostname: db
    env_file:
      - docker/postgres.env
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
 
  django:
    build: .
    hostname: django
    # restart: always
    # command: /wait_for_postgres.sh
    user: 'video_user'
    depends_on:
      - db
    env_file:
      - docker/django.env
    ports:
      - 8000:8000
    volumes:
      - ./:/app
