# Generated by Django 3.0.2 on 2020-03-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='path',
        ),
        migrations.AddField(
            model_name='movie',
            name='file',
            field=models.FileField(default=1, max_length=240, upload_to='static', verbose_name='Archivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='Test', max_length=240, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
